######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 30 21:18:00 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += qsmoothscrollarea.h
SOURCES += main.cpp qsmoothscrollarea.cpp
